# example 1: on push to master
name: Bump version
on:
  push:
    branches:
      - master

jobs:
#   build:
#     runs-on: ubuntu-22.04
#     permissions:
#       contents: write
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         fetch-depth: '0'

#     - name: Bump version and push tag
#       uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
#         WITH_V: false
  release-project:
       name: Node-app relese
       environment: 
        name: PRODUCTION
       runs-on: ubuntu-latest
       steps: 
       
       - uses: actions/checkout@v2

       - name: Tag
         id: tag_version
         uses: gdo-dentsu-creative-web/github-tag-action@v6.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           release_branches: master*
       
       - name: Create a GitHub release
         id: master
         uses: gdo-dentsu-creative-web/release-action@v1
         with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          release: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

       - name: Download artifact from build job
         uses: actions/download-artifact@v2
         with:
          name: node-app

       - name: Upload asset to Release
         uses: actions/upload-release-asset@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
         with:
           upload_url: ${{ steps.master.outputs.upload_url }} 
           asset_path: ${{ github.workspace }}/release.zip
           asset_name: ${{ steps.tag_version.outputs.new_tag }}.zip
           asset_content_type: application/zip
