name: Custom Tagging

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "hardik.sharma@successive.tech"
          git config --local user.name "@Hardikss"

      - name: Create tag
        id: create_tag
        run: |
          git tag -a v1.0.0 -m "Version 1.0.0"
          git push origin --tags

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.stdout }}
          release_name: Release ${{ steps.create_tag.outputs.stdout }}
          body: |
            Add release notes here.




