name: Create Tag and Release

on:
  push:
    branches:
      - master


jobs:
    release-project:
       name: Node-app relese
       runs-on: ubuntu-latest
       steps: 
       
       - uses: actions/checkout@v2

       - name: Tag
         id: tag_version
         uses: mathieudutour/github-tag-action@v6.0
         with:
           github_token: ${{ secrets.GH_TOKEN }}
           release_branches: master*
       
       - name: Create GitHub Release
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag: v1.0.0
           release: Release v1.0.0
           body: Add release notes here
  
       - name: Download artifact from build job
         uses: actions/download-artifact@v2
         with:
          name: node-app
 
       - name: Upload Release Asset
         id: upload-release-asset 
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.master.outputs.upload_url }} 
           asset_path: ${{ github.workspace }}/release.zip
           asset_name: ${{ steps.tag_version.outputs.new_tag }}.zip
           asset_content_type: application/zip
