name: Tag and Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Your Name"
          git config user.email "your.email@example.com"

      - name: Get current tag (if available)
        id: get_tag
        run: |
          TAG=$(git describe --abbrev=0 --tags 2>/dev/null || echo "")
          echo "::set-output name=tag::$TAG"

      - name: Determine next tag
        id: increment_tag
        run: |
          CURRENT_TAG=${{ steps.get_tag.outputs.tag }}
          if [[ -z "$CURRENT_TAG" ]]; then
            NEXT_TAG="v1.0.0"
          else
            IFS='.' read -r -a VERSION <<< "$CURRENT_TAG"
            MAJOR=${VERSION[0]}
            MINOR=${VERSION[1]}
            PATCH=${VERSION[2]}
            NEXT_TAG="$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          echo "::set-output name=tag::$NEXT_TAG"

      - name: Create and push tag
        id: create_tag
        run: |
          NEXT_TAG=${{ steps.increment_tag.outputs.tag }}
          git tag $NEXT_TAG
          git push origin $NEXT_TAG

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: Release ${{ steps.create_tag.outputs.tag }}
          body: |
            Add release notes here
          draft: false
          prerelease: false
