name: Custom Tagging

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "hardik.sharma@successive.tech"
          git config --local user.name "@Hardikss"

      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Bump tag
        id: bump_tag
        run: |
          git tag -a "$(echo ${{ steps.latest_tag.outputs.tag }} | awk -F. -v OFS=. '{$NF=$NF+1;} 1')" -m "Bump version"
          git push --follow-tags
