name: Bump version
on:
  push:
    branches:
      - master


jobs:
  tag:
    name: Move major tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: phwt/major-tagging-action@v1
