name: Determine Next Tag

on:
  push:
    branches:
      - master

jobs:
  determine_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-version:refname | head -n 1)
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Extract tag version
        id: extract_tag_version
        run: |
          version=$(echo "${{ steps.get_latest_tag.outputs.latest_tag }}" | sed -E 's/^v([0-9.]+).*$/\1/')
          echo "::set-output name=version::$version"

      - name: Increment tag version
        id: increment_tag_version
        run: |
          version="${{ steps.extract_tag_version.outputs.version }}"
          next_version=$(echo "$version + 0.1" | bc)
          echo "::set-output name=next_version::$next_version"

      - name: Use next tag
        run: |
          next_tag="${{ steps.increment_tag_version.outputs.next_version }}"
          echo "Next Tag: $next_tag"

