name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Increment tag
        id: increment_tag
        uses: mathieudutour/github-tag-action@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.increment_tag.outputs.new_tag }}
          name: Release ${{ steps.increment_tag.outputs.new_tag }}
          body: |
            Add release notes here
          draft: false
          prerelease: false
