# example 2: on merge to master
name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }} # required for better experience using pre-releases
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
        PRERELEASE: true



# name: CI + CD 

# on:
#   push:
#     branches: [ master ]

#   workflow_dispatch:

# jobs:
#   Build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Compile
#         run: echo Hello, world!
    
#   DeployDev:
#     name: Deploy to Dev 
#     if: github.event_name == 'pull_request'
#     needs: [Build]
#     runs-on: ubuntu-latest
#     environment: 
#       name: Development
#       url: 'http://dev.myapp.com'
#     steps:
#       - name: Deploy
#         run: echo I am deploying! 
    
#   DeployStaging:
#     name: Deploy to Staging 
# #     if: github.event.ref == 'refs/heads/main'
#     needs: [Build]
#     runs-on: ubuntu-latest
#     environment: 
#       name: Staging
#       url: 'http://test.myapp.com'
#     steps:
#       - name: Deploy
#         run: echo I am deploying! 
            
#   DeployProd:
#     name: Deploy to Production 
#     needs: [DeployStaging]
#     runs-on: ubuntu-latest
#     environment: 
#       name: Production
#       url: 'http://www.myapp.com'
#     steps:
#       - name: Deploy
#         run: echo I am deploying! 
