name: Custom Tagging

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "hardik.sharma@successive.tech"
          git config --local user.name "@Hardikss"

      - name: Get previous tag
        id: get_previous_tag
        run: |
          git checkout $(Build.SourceBranchName)
          git fetch --tags
          VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          oldVer=$VERSION
          echo "::set-output name=tag::$PREVIOUS_TAG"

      - name: Increment tag
        id: increment_tag
        run: |
          PVERSION_BITS=(${VERSION//./ })
          #get number parts and increase last one by 1
          NUM1=${VERSION_BITS[0]} # for Major number increse
          NUM2=${VERSION_BITS[1]} # Minor Number increse
          NUM3=${VERSION_BITS[2]} #Patch number increse
          NUM3=$((NUM3+1))

      - name: Create tag
        id: create_tag
        run: |
          TNEW_TAG="$NUM1.$NUM2.$NUM3"
          echo "Updating $VERSION to $NEW_TAG"
          newVer=$NEW_TAG
