name: Custom Tagging

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "hardik.sharma@successive.tech"
          git config --local user.name "@Hardikss"

      - name: Get previous tag
        id: get_previous_tag
        run: |
          git fetch --tags
          PREVIOUS_TAG=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag::$PREVIOUS_TAG"

      - name: Increment tag
        id: increment_tag
        run: |
          PREVIOUS_TAG=${{ steps.get_previous_tag.outputs.tag }}
          IFS='.' read -r -a VERSION <<< "$PREVIOUS_TAG"
          MAJOR=${VERSION[0]}
          MINOR=${VERSION[1]}
          PATCH=${VERSION[2]}
          NEW_TAG="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "::set-output name=tag::$NEW_TAG"

      - name: Create tag
        id: create_tag
        run: |
          TAG=${{ steps.increment_tag.outputs.tag }}
          git tag $TAG
          git push origin $TAG
