name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: tag-release
#       - uses: actions/checkout@v2
#       - name: Bump version and push tag
#         id: tag_version
        uses: halvardssm/github-action-tag-release@1.0.0

          
