name: Auto Increment Tag and Create Release

on:
  push:
    branches:
      - master

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14

#       - name: Install dependencies
#         run: npm install

      - name: Get latest tag
        id: get_latest_tag
        run: echo "::set-output name=latest_tag::$(git describe --abbrev=0 --tags)"

      - name: Increment tag
        id: increment_tag
        uses: mathieudutour/github-tag-action@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.increment_tag.outputs.new_tag }}
          name: Release ${{ steps.increment_tag.outputs.new_tag }}
          body: |
            Add release notes here
          draft: false
          prerelease: false
