name: Auto Increment Tag

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current tag (if available)
        id: get_tag
        run: |
          TAG=$(git describe --abbrev=0 --tags 2>/dev/null || echo "")
          echo "::set-output name=tag::$TAG"

      - name: Determine next tag
        id: increment_tag
        run: |
          CURRENT_TAG=${{ steps.get_tag.outputs.tag }}
          if [[ -z "$CURRENT_TAG" ]]; then
            NEXT_TAG="v1.0.0"
          else
            IFS='.' read -r -a VERSION <<< "$CURRENT_TAG"
            MAJOR=${VERSION[0]}
            MINOR=${VERSION[1]}
            PATCH=${VERSION[2]}
            NEXT_TAG="$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          echo "::set-output name=tag::$NEXT_TAG"

      - name: Create tag
        id: create_tag
        run: |
          NEXT_TAG=${{ steps.increment_tag.outputs.tag }}
          git tag $NEXT_TAG
          git push origin $NEXT_TAG
