name: Upload Release Asset

on:
  push:
    branches:
      - master

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete Workflow Runs
        uses: actions/github-script@v5
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            
            const octokit = new Octokit({
              auth: process.env.GITHUB_TOKEN
            });
            
            async function deleteWorkflowRuns() {
              const owner = "your-username";
              const repo = "your-repository";
              const workflowId = "your-workflow-id";
              const daysToKeep = 7; // Number of days to keep workflow runs
            
              const { data: runs } = await octokit.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id: workflowId,
                status: "completed",
                per_page: 100
              });
            
              const cutoffDate = new Date();
              cutoffDate.setDate(cutoffDate.getDate() - daysToKeep);
            
              for (const run of runs) {
                const runDate = new Date(run.updated_at);
            
                if (runDate < cutoffDate) {
                  await octokit.rest.actions.deleteWorkflowRun({
                    owner,
                    repo,
                    run_id: run.id
                  });
                  
                  console.log(`Deleted workflow run ${run.id}`);
                }
              }
            }
            
            deleteWorkflowRuns();
