name: Custom Tagging

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "hardik.sharma@successive.tech"
          git config --local user.name "@Hardikss"


      - name: Determine next tag
        id: increment_tag
        run: |
          CURRENT_TAG=${{ env.CURRENT_TAG }}
          IFS='.' read -r -a VERSION <<< "$CURRENT_TAG"
          MAJOR=${VERSION[0]}
          MINOR=${VERSION[1]}
          PATCH=${VERSION[2]}
          NEXT_TAG="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "::set-output name=tag::$NEXT_TAG"

      - name: Create tag
        id: create_tag
        run: |
          NEXT_TAG=${{ steps.increment_tag.outputs.tag }}
          git tag $NEXT_TAG
          git push origin $NEXT_TAG

      - name: Set next tag as current tag for next build
        run: |
          NEXT_TAG=${{ steps.increment_tag.outputs.tag }}
          echo "CURRENT_TAG=$NEXT_TAG" >> $GITHUB_ENV


